// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ozpcuahrauxordfgaovv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im96cGN1YWhyYXV4b3JkZmdhb3Z2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk0Njc1NjAsImV4cCI6MjA2NTA0MzU2MH0.6j8-_M03NGOJQuC1ri00TIoAFLpjkoiVGkRzdMpqGno";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);